"""create_kpi_tables

Revision ID: 1811d467c578
Revises: b2c3d4e5f6a7
Create Date: 2026-04-24 14:40:19.932794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1811d467c578'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.Enum('SALES', 'MARKETING', 'FINANCE', 'HR', 'OPERATIONS', 'ENGINEERING', 'CUSTOMER_SUCCESS', 'PRODUCT', 'LEGAL', 'GENERAL', name='departmentcategory'), nullable=False),
    sa.Column('unit', sa.Enum('PERCENTAGE', 'CURRENCY', 'COUNT', 'SCORE', 'RATIO', 'DURATION_HOURS', 'CUSTOM', name='measurementunit'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'ON_DEMAND', name='measurementfrequency'), nullable=False),
    sa.Column('scoring_direction', sa.Enum('HIGHER_IS_BETTER', 'LOWER_IS_BETTER', name='scoringdirection'), nullable=False),
    sa.Column('suggested_formula', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', name='uq_kpi_tag_name_org')
    )
    op.create_table('kpi_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.Enum('SALES', 'MARKETING', 'FINANCE', 'HR', 'OPERATIONS', 'ENGINEERING', 'CUSTOMER_SUCCESS', 'PRODUCT', 'LEGAL', 'GENERAL', name='departmentcategory'), nullable=False),
    sa.Column('colour_hex', sa.String(length=7), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('PERCENTAGE', 'CURRENCY', 'COUNT', 'SCORE', 'RATIO', 'DURATION_HOURS', 'CUSTOM', name='measurementunit'), nullable=False),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'ON_DEMAND', name='measurementfrequency'), nullable=False),
    sa.Column('data_source', sa.Enum('MANUAL', 'FORMULA', 'INTEGRATION', name='datasourcetype'), nullable=False),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('scoring_direction', sa.Enum('HIGHER_IS_BETTER', 'LOWER_IS_BETTER', name='scoringdirection'), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='kpistatus'), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_organisation_wide', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['kpi_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_kpi_org_code')
    )
    op.create_index('ix_kpi_category', 'kpis', ['category_id'], unique=False)
    op.create_index('ix_kpi_org_status', 'kpis', ['organisation_id', 'status'], unique=False)
    op.create_table('kpi_formula_dependency',
    sa.Column('parent_kpi_id', sa.UUID(), nullable=False),
    sa.Column('dependency_kpi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_kpi_id', 'dependency_kpi_id')
    )
    op.create_table('kpi_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_tag_association',
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['kpi_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kpi_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_tag_association')
    op.drop_table('kpi_history')
    op.drop_table('kpi_formula_dependency')
    op.drop_index('ix_kpi_org_status', table_name='kpis')
    op.drop_index('ix_kpi_category', table_name='kpis')
    op.drop_table('kpis')
    op.drop_table('kpi_categories')
    op.drop_table('kpi_tags')
    op.drop_table('kpi_templates')
    # ### end Alembic commands ###
