"""add_kpi_scoring_configs_and_overrides

Revision ID: 7a3138160dbf
Revises: 4f0457820297
Create Date: 2026-04-27 11:22:04.349888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3138160dbf'
down_revision: Union[str, None] = '4f0457820297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_scoring_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('preset', sa.Enum('STANDARD', 'STRICT', 'LENIENT', 'BINARY', 'SALES', 'CUSTOM', name='scoringpreset'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('exceptional_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('exceeds_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('meets_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('partially_meets_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('does_not_meet_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('achievement_cap', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('adjustment_justification_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_system_preset', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('kpi_targets', sa.Column('scoring_config_id', sa.UUID(), nullable=True, comment="Target-level override. Highest precedence. Falls back to KPI's config, then cycle config."))
    op.create_foreign_key(None, 'kpi_targets', 'kpi_scoring_configs', ['scoring_config_id'], ['id'], ondelete='SET NULL')
    op.add_column('kpis', sa.Column('scoring_config_id', sa.UUID(), nullable=True, comment='Default scoring config for this KPI. Overridden by target-level config.'))
    op.create_foreign_key(None, 'kpis', 'kpi_scoring_configs', ['scoring_config_id'], ['id'], ondelete='SET NULL')
    op.add_column('performance_scores', sa.Column('scoring_config_snapshot', sa.JSON(), nullable=True, comment='Snapshot of the effective scoring config at time of computation.'))
    op.add_column('performance_scores', sa.Column('rating_config_source', sa.String(length=100), nullable=True, comment="Which config level was used: 'target_override:X', 'kpi_default:X', or 'cycle_default'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_scores', 'rating_config_source')
    op.drop_column('performance_scores', 'scoring_config_snapshot')
    op.drop_constraint(None, 'kpis', type_='foreignkey')
    op.drop_column('kpis', 'scoring_config_id')
    op.drop_constraint(None, 'kpi_targets', type_='foreignkey')
    op.drop_column('kpi_targets', 'scoring_config_id')
    op.drop_table('kpi_scoring_configs')
    # ### end Alembic commands ###
