"""create_targets_actuals_review_cycles_tables

Revision ID: 8c420a93904d
Revises: 1811d467c578
Create Date: 2026-04-24 18:43:47.801406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c420a93904d'
down_revision: Union[str, None] = '1811d467c578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cycle_type', sa.Enum('ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY', 'CUSTOM', name='cycletype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED', name='cyclestatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('target_setting_deadline', sa.Date(), nullable=True),
    sa.Column('actual_entry_deadline', sa.Date(), nullable=True),
    sa.Column('scoring_start_date', sa.Date(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_cycle_dates', 'review_cycles', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_review_cycle_org_status', 'review_cycles', ['organisation_id', 'status'], unique=False)
    op.create_table('kpi_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('review_cycle_id', sa.UUID(), nullable=False),
    sa.Column('assignee_type', sa.Enum('ORGANISATION', 'DEPARTMENT', 'TEAM', 'INDIVIDUAL', name='targetlevel'), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('assignee_org_id', sa.UUID(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stretch_target_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('minimum_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_ACKNOWLEDGEMENT', 'ACKNOWLEDGED', 'APPROVED', 'LOCKED', name='targetstatus'), nullable=False),
    sa.Column('cascade_parent_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('set_by_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cascade_parent_id'], ['kpi_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['review_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kpi_target_assignee_user', 'kpi_targets', ['assignee_user_id'], unique=False)
    op.create_index('ix_kpi_target_kpi', 'kpi_targets', ['kpi_id'], unique=False)
    op.create_index('ix_kpi_target_review_cycle', 'kpi_targets', ['review_cycle_id'], unique=False)
    op.create_index('ix_kpi_target_status', 'kpi_targets', ['status'], unique=False)
    op.create_table('kpi_actuals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('entry_source', sa.Enum('MANUAL', 'AUTO_FORMULA', 'AUTO_INTEGRATION', name='actualentrysource'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='actualentrystatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['kpi_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kpi_actual_kpi', 'kpi_actuals', ['kpi_id'], unique=False)
    op.create_index('ix_kpi_actual_status', 'kpi_actuals', ['status'], unique=False)
    op.create_index('ix_kpi_actual_target_period', 'kpi_actuals', ['target_id', 'period_date'], unique=False)
    op.create_table('target_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('milestone_date', sa.Date(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['kpi_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_target_milestone_target', 'target_milestones', ['target_id'], unique=False)
    op.create_table('actual_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actual_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actual_id'], ['kpi_actuals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actual_evidence_actual', 'actual_evidence', ['actual_id'], unique=False)
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_actual_evidence_actual', table_name='actual_evidence')
    op.drop_table('actual_evidence')
    op.drop_index('ix_target_milestone_target', table_name='target_milestones')
    op.drop_table('target_milestones')
    op.drop_index('ix_kpi_actual_target_period', table_name='kpi_actuals')
    op.drop_index('ix_kpi_actual_status', table_name='kpi_actuals')
    op.drop_index('ix_kpi_actual_kpi', table_name='kpi_actuals')
    op.drop_table('kpi_actuals')
    op.drop_index('ix_kpi_target_status', table_name='kpi_targets')
    op.drop_index('ix_kpi_target_review_cycle', table_name='kpi_targets')
    op.drop_index('ix_kpi_target_kpi', table_name='kpi_targets')
    op.drop_index('ix_kpi_target_assignee_user', table_name='kpi_targets')
    op.drop_table('kpi_targets')
    op.drop_index('ix_review_cycle_org_status', table_name='review_cycles')
    op.drop_index('ix_review_cycle_dates', table_name='review_cycles')
    op.drop_table('review_cycles')
    # ### end Alembic commands ###
